<!DOCTYPE HTML>
<html>
<head>     
     <meta charset="utf-8" />
     <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
      <link href="tmp/img/style.css" rel="stylesheet" type="text/css" />
     <style type="text/css">
     .SYSTEM{
          
     }
     .ERROR{
          background: red;
     }
     </style>

</head>
<title><?=LOC_TITLE_PAGE;?></title>
<body>
 <div id="wrapper">
          <div id="headBox">Верхний блок</div>
          <div id="invisibleBox"></div>
          <div id="contentPosts">
                 
                 <button id="GetPosts"><?=LOC_BUTTON_GET_POSTS;?></button>        
          </div>                            
                  
          <div id="rightBox">
          <?=TMP_RIGHT_PANEL; ?>
               <?=LOC_AUT; //Выводить статус пользователя?>  <br />
          </div>
     </div>

<script type="text/javascript" src="ajaxNEW.js"></script>
</body>
</html>