<!DOCTYPE HTML>
<html>
<head>
     <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
     <style type="text/css">
     .SYSTEM{
          
     }
     .ERROR{
          background: red;
     }
     </style>
</head>
<title><?=LOC_TITLE_PAGE;?></title>
<body>
<?=LOC_AUT;?>
<div id="all">
</div>

<a id='exit'><?=LOC_BUTTON_UNLOGIN;?></a>
<a href="#" id="GetPosts"><?=LOC_BUTTON_GET_POSTS;?></a>

<textarea id="textPost"></textarea>
<input id="sendPost" type="button" />
<script type="text/javascript" src="ajaxNEW.js"></script>
</body>
</html>